services:
  apache_php:
    build: .
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./.env:/var/www/html/.env
    develop:
      watch:
        - path: .
          target: /var/www/html/
          ignore: 
            - .git/
            - node_modules/
            - vendor/
          action: sync
        - path: composer.json
          action: rebuild

  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
